[env:um_pros3]
platform = espressif32
board = um_pros3
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 921600

board_build.filesystem = littlefs
board_build.partitions = default_8MB.csv

build_flags =
    ; 1. Disable the internal USB stack's default handling
    -D ARDUINO_USB_MODE=1 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    
    ; 2. Tell the system we are using the TinyUSB library explicitly
    -D USE_TINYUSB

    ; 3. Other config flags
    -D USE_NIMBLE
    -D FASTLED_ESP32_S3

; ! IMPORTANT: Tell the Linker to ignore duplicate symbols if they arise
build_unflags = -D ARDUINO_USB_MODE=0

lib_archive = no

lib_deps =
    adafruit/Adafruit TinyUSB Library @ ^3.3.0
    bblanchon/ArduinoJson @ ^7.0.3
    h2zero/NimBLE-Arduino @ ^1.4.1
    olikraus/U8g2 @ ^2.35.9
    fastled/FastLED @ ^3.6.0
    mathertel/RotaryEncoder @ ^1.5.3
    chris--a/Keypad @ ^3.1.1
